# Shown behind the "Sponsor" button on the repository page.
ko_fi: majstorov
custom:
  - "https://buy.polar.sh/polar_cl_zPF9CaYg2iyuHxQ3hA3mdXVvomRJb8gEzC5d93f8xfV"
  - "https://buy.polar.sh/polar_cl_G3W6En67QTEVoBC1oVln4HQqcpqK8w7vujkJD4WjGOj"
  - "https://www.paypal.com/paypalme/majstorov"
